### ISSUE TITLE
Copy arbitrary selected HTML content as Org-mode

### ISSUE THREAD

**Issue by novoid** [kuanyui/copy-as-org#1]
Hi!

I am _very_ thankful for your wonderful add-on. It serves me very well each day and I love the possibility to copy HTML tables to my Org-mode.

However, I wonder if your method has the potential to copy arbitrary selected HTML content to Org-mode format. Let's say I mark a title, a paragraph with **formatted** _text_ elements including links, a table, a list, and so forth in my Firefox. Then I select "Copy as Org-mode" and so I can paste it to my Emacs in Org-mode syntax.

Is this far fetched or does your method provide this as well in the future?

Thanks!

**Comment by kuanyui** [comment]
I indeed had this idea when writing copy-as-org-mode, but had no enough motivation (because I don't need). If you like, surely, welcome to fork and make a PR :-)

**Comment by alphapapa** [comment]
@novoid Not to trample on this project, but you can do what you ask using http://github.com/alphapapa/org-protocol-capture-html  :)

**Comment by novoid** [comment]
@alphapapa Thanks for the pointer!

I knew org-protocol-capture (not using it) but I was not aware that it is possible to copy just the selection and not the whole page.
I'll set it up and try it.

However, copy-as-org-mode with my proposed enhancement(s) would simplify the setup and usage of this feature IMO.

If @kuanyui is not going to implement this, then he is free to close this issue since we clarified on this for now. Maybe someone else (not me due to lack of knowledge) is stumbling over this thread and hands in a merge request :-)

**Comment by azzamsa** [comment]
@novoid, Not to trample on this project. But to help novoid. Temporarily you can use alphapapa suggestion, or you can use [html2txt](https://github.com/Alir3z4/html2text) than [using pandoc](https://stackoverflow.com/a/46610786/6000005) to convert to org-mode

**Comment by novoid** [comment]
Today, I tried again to set-up `org-protocol-capture-html` on my Windows 10 machine. Unfortunately, I failed with "Warning (emacs): Please update your Org Protocol handler to deal with new-style links.". I'll have to research what this message means.

However, independent of any working or non-working alternatives (thanks for the links!), I still would love to see this functionality with `copy-as-org-mode` as well ;-)

**Comment by alphapapa** [comment]
@novoid I fixed that issue on my end about a year ago: https://github.com/alphapapa/org-protocol-capture-html/issues/14  However, there was also an issue in Org that caused that error to appear.  I posted about it on the Org list several months ago and IIRC a fix was made.  Are you using the latest version of Org?

**Comment by novoid** [comment]
I'm using Org mode version 9.0.3 (release_9.0.3-1236-gd3f730) from git/maint d3f7309cb (3 months ago).

**Comment by alphapapa** [comment]
I'm on 9.0.5.  I can't say whether that will fix the problem, but you might try upgrading.

**Comment by novoid** [comment]
@alphapapa: I'm now on Org 9.1.6 which is the most current git/maint.

However, it was my fault that the message above occurred. I'm sorry for taking an outdated shortcut for testing the command. I now understand the implications of this.

However, when I invoke the org-protocol javascript bookmarklet on a web page (not an empty tab or the about page of Firefox), I now get an open new Emacs buffer for `c:/Program Files (x86)/Mozilla Firefox/org-protocol:/capture-html/?template=l&url=about%%3Ablank&title=%%5Buntitled%%20page%%5D&body=`

Mysterious to me 😉

Well, since this does not seem to relate to copy-as-org-mode, I opened [this issue](https://github.com/alphapapa/org-protocol-capture-html/issues/26) instead.

I don't close this issue here since we got side-tracked and my original feature-wish of using copy-as-org-mode for copying all kinds of HTML selections and paste it into Org-mode via clipboard is still valid in my view.

**Comment by azzamsa** [comment]
@novoid see https://github.com/chitsaou/copy-as-markdown/issues/52#issuecomment-370126332

**Comment by novoid** [comment]
@azzamsa: Thanks for the pointer. I've took a look at this (and similar) add-on. Unfortunately, they're not solving my issue here because they only copy the page URL and/or a selection without formatting.

Instead, I'd like to select a itemized list of a page together with a paragraph and a table. When invoking the copy command and pasting it into Emacs, I want to then get an Org-mode list with an Org-mode paragraph and the corresponding Org-mode table. All elements contain HTML-links (if there are any in the HTML source) as Org-mode links as well.

So there are different requirements.

**Comment by kuanyui** [comment]
This repo has been deprecated and about to be archived because this is for old / legacy Firefox.
For latest Firefox (WebExtension), please see https://github.com/kuanyui/copy-as-org-mode

The feature you mentioned in this issue should also be implemented now.
If you feel this work is usable for you, please consider to donate, at least I spent 5 days of my life on it.
