### ISSUE TITLE
Plugin blocks e10s

### ISSUE THREAD

**Issue by kamidon** [kuanyui/copy-as-org#2]
This plugin currently blockes e10s support. It would be nice if that could be resolved, although converting it to a WebExtension looks like a complete rewrite that may not even be possible with existing extensions and even supporting e10s may not be possible because of the use of the window API.

**Comment by kuanyui** [comment]
Sorry, I have no free time to do this currently. I have lots of other more important tasks and projects waiting me to finish.

**Comment by azzamsa** [comment]
Good Luck for your primary projects Kuanyui. 
Hope this extension can be ported to WebExtension one day.

Thanks lot.

**Comment by azzamsa** [comment]
@kamidon , for a while I use [copy-as-markdown](https://github.com/chitsaou/copy-as-markdown/) to my org-mode buffer, than use keybinding to invoke this simple script [make-md-to-org](https://github.com/azzamsa/emacs.d/blob/master/myelisp/make-md-to-org.el).

**Comment by kamidon** [comment]
@azzamsa, thanks for the suggestion, it sounds like a good solution for more general requirements than I have. I primarily use org-capture with a bookmarklet to capture links to tabs I want to be able to revisit from something I'm tracking in org. This works well for most things, with the on exception of github, where for some reason the cross-site scripting configuration prevents the use of the bookmarklet. It was in this situation that I used copy-as-org-mode. For now I'm just manually creating the links in this one case. Thanks again!

**Comment by azzamsa** [comment]
See also [org-cliplink: Insert org-mode links from clipboard](https://github.com/rexim/org-cliplink)

**Comment by azzamsa** [comment]
If anyone using [saka-key](https://key.saka.io/dev_docs/), I added some [customization](https://github.com/azzamsa/saka-key/commit/2919a2a160d200f2c5cd1c3568d2ac16c79effb3) to make `y o` key press send page title and url as org-mdoe format

**Comment by kuanyui** [comment]
This repo has been deprecated because this is for old / legacy Firefox.
For latest Firefox (WebExtension), please see https://github.com/kuanyui/copy-as-org-mode
