### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by azzamsa** [kuanyui/copy-as-org#3]
This plugin really save my time. I used to work with firefox and org all the day. So I have to do everything manually before I know this app.

Thanks lot. thanks.

**Comment by kuanyui** [comment]
You should thanks the author of `copy-as-markdown` @chitsaou. What I've done is adding the supporting of `<table>`.
And I've no free time and patience and interests to port this addon to WebExtension currently...

**Comment by kuanyui** [comment]
This repo has been deprecated and about to be archived because this is for old / legacy Firefox.
For latest Firefox (WebExtension), please see https://github.com/kuanyui/copy-as-org-mode.
If you feel this work is usable for you, please consider to donate.

**Comment by kuanyui** [comment]
This repo has been deprecated and about to be archived because this is for old / legacy Firefox.
For latest Firefox (WebExtension), please see https://github.com/kuanyui/copy-as-org-mode.
If you feel this work is usable for you, please consider to donate. :smiley:
